P = pwd;
P1 = [P,'/TrackingSimu/'];
P2 = [P,'/heterosolver/'];
P3 = [P,'/demo/'];
P4 = [P,'/ink/'];
P5 = [P,'/evaluation/'];
P6 = [P,'/fullsimu/'];
P7 = [P,'/scenariosimu/'];
P8 = [P,'/paratunning/'];
P9 = [P,'/forfalcon/'];
P10= [P,'/dataset/'];
P11= [P,'/forMTT/'];
P12= [P,'/heterosolverlinking/'];
P13= [P,'/visual/'];
P14= [P,'/math/'];
P15= [P,'/trjprocessing/'];
P16= [P,'/foruser/'];
P17= [P,'/TrackingSimu/SimuTracksPoisson/'];

addpath(P1);
addpath(P2);
addpath(P3);
addpath(P4);
addpath(P5);
addpath(P6);
addpath(P7);
addpath(P8);
addpath(P9);
addpath(P10);
addpath(P11);
addpath(P12);
addpath(P13);
addpath(P14);
addpath(P15);
addpath(P16);
addpath(P17);

clear P;
clear P1;
clear P2;
clear P3;
clear P4;
clear P5;
clear P6;
clear P7;
clear P8;
clear P9;
clear P10;
clear P11;
clear P12;
clear P13;
clear P14;
clear P15;
clear P16;
clear P17;